from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from typing import Literal

from app.config import AppConfig
from app.db.database import connect
from app.services.model_bus import ChatMessage, ModelBus
from app.services.transcript_quality import safe_transcript_text
from pydantic import BaseModel, Field, field_validator

LOGGER = logging.getLogger(__name__)


class ExtractedAction(BaseModel):
    owner: str | None = None
    task: str
    due_date: str | None = None
    # Segment id where the due date phrase was spoken. Lets the dashboard
    # jump-to-evidence on "due by Friday" so the user can verify the model
    # parsed it correctly. Null when due_date itself is null or the source
    # is ambiguous (a date stated in passing not tied to one segment).
    due_date_source: int | None = None
    priority: str = "normal"
    source_segment_ids: list[int] = Field(default_factory=list)


class ExtractedDecision(BaseModel):
    decision: str
    # One-sentence WHY the decision was made (trade-off considered,
    # constraint cited, evidence that tipped it). Optional — legacy payloads
    # predate this field and the model is allowed to leave it null when
    # no rationale was stated. Decision logs without rationale rot fastest,
    # so the prompt pushes the model to infer from surrounding context
    # when the speaker didn't say "because" explicitly.
    rationale: str | None = None
    source_segment_ids: list[int] = Field(default_factory=list)


class ExtractedOpenQuestion(BaseModel):
    """A question raised in the meeting that wasn't fully resolved.

    Promoted from a flat string list to a structured object so the dashboard
    can show status pills, attribute questions back to the speaker who
    raised them, and feed Phase B+ Conversation Drivers / Reflections.
    Legacy persisted records used `{"text": "..."}`; readers handle both.
    """

    question: str
    # Speaker who raised the question (approved name when available, else
    # null when the transcript is ambiguous).
    raised_by: str | None = None
    # Speaker the question was directed at, when explicit ("Avery, what's
    # the rollout timeline?"). Null for broadcast questions.
    addressed_to: str | None = None
    # unanswered: no on-topic response within the next ~90s of transcript.
    # partially_answered: a response came but didn't resolve the question.
    # deferred: someone explicitly said "let's come back to this" or
    # "park it."
    status: Literal["unanswered", "partially_answered", "deferred"] = "unanswered"
    source_segment_ids: list[int] = Field(default_factory=list)


class ExtractedWorkstream(BaseModel):
    name: str
    description: str = ""
    confidence: float = 0.5
    source_segment_ids: list[int] = Field(default_factory=list)


class ParticipantContribution(BaseModel):
    """Per-attendee distillation rendered as the canonical Minutes view.

    Replaces "transcript-grouped-by-chapter" Minutes (which duplicated
    the Transcript tab) with a "what did each person bring to this
    meeting" surface.
    """

    speaker: str
    contribution: str
    source_segment_ids: list[int] = Field(default_factory=list)


class StatCallout(BaseModel):
    """Big-number highlight surfaced on the Mind Map as a stat card.

    The model picks 0-3 of the most-interesting numerical claims in the
    meeting (durations, dollar amounts, percentages, counts) and renders
    them with disproportionate visual weight in the dashboard.
    """

    value: str
    label: str
    source_segment_ids: list[int] = Field(default_factory=list)


class TensionPoint(BaseModel):
    """A moment in the meeting where two sides emerged.

    Surfaces as a sentiment-split card on the Mind Map. Most meetings
    have zero or one; the model only emits a tension when there's a
    real either/or in the transcript, not synthetic conflict.
    """

    title: str
    positive_side: str
    negative_side: str
    source_segment_ids: list[int] = Field(default_factory=list)


class ChapterMarker(BaseModel):
    """Time-anchored chapter label for the Transcript chapter rail.

    Generated by the LLM in the same extract call rather than derived
    heuristically on the frontend. Label is capped at 7 words by the
    prompt so the rail reads as labels, not paragraphs. start_segment_id
    is the segment that opens the chapter.
    """

    label: str
    start_segment_id: int
    # One-sentence skim of what happens in this chapter. Optional — legacy
    # records predate this field, and the model returns "" when a chapter
    # is too short to summarise meaningfully. Useful both for human skim
    # in the Time-Minutes view and as context for downstream passes
    # (Conversation Drivers, Reflections).
    summary: str = ""


class ExecutiveRecapBullet(BaseModel):
    """One commitment in the strategy section. `purpose` ties the
    commitment to the meeting's strategic through-line; null is allowed
    (and preferred over a fabricated rationale) when the commitment is
    tangential or the meeting had no coherent through-line.
    """

    owner: str
    commitment: str
    purpose: str | None = None


class ExecutiveRecapSection(BaseModel):
    """Header/body pair for a recap section. Both may be null only in
    the optional risk section — the reframe and strategy sections are
    always populated (fallback prompts cover degenerate cases).
    """

    header: str | None = None
    body: str | None = None


class ExecutiveRecapStrategy(BaseModel):
    header: str | None = None
    body: str | None = None
    bullets: list[ExecutiveRecapBullet] = Field(default_factory=list)
    # One-sentence aside about something deferred / parked / scoped out.
    # Optional — most meetings don't have one.
    trailer: str | None = None


class ExecutiveRecap(BaseModel):
    """Plaud-style narrative recap synthesized from MeetingAtoms.
    Three sections: reframe (editorial), strategy (commitments framed
    as one plan), risk (conservative voice, optional).
    """

    reframe: ExecutiveRecapSection
    strategy: ExecutiveRecapStrategy
    risk: ExecutiveRecapSection = Field(default_factory=ExecutiveRecapSection)


class MeetingAtoms(BaseModel):
    suggested_title: str
    # Wire-thin headline shown at the very top of the meeting page.
    # The fuller `summary` lives below it; this is the one-glance hook.
    # Required (no default) so json-schema enforcement makes the model
    # emit it instead of picking the empty-string fallback.
    tldr: str
    summary: str
    actions: list[ExtractedAction] = Field(default_factory=list)
    decisions: list[ExtractedDecision] = Field(default_factory=list)
    workstreams: list[ExtractedWorkstream] = Field(default_factory=list)
    participant_contributions: list[ParticipantContribution] = Field(default_factory=list)
    chapter_markers: list[ChapterMarker] = Field(default_factory=list)
    themes: list[str] = Field(default_factory=list)
    stat_callouts: list[StatCallout] = Field(default_factory=list)
    tension_points: list[TensionPoint] = Field(default_factory=list)
    open_questions: list[ExtractedOpenQuestion] = Field(default_factory=list)
    uncertainties: list[str] = Field(default_factory=list)
    # 3-5 model-curated takeaways that someone who wasn't in the meeting
    # would need to know. Distinct from `summary` (narrative prose) and
    # `tldr` (single hook): these are the bullets a reader would write
    # in an email after the call. Anchored to substance, not moments.
    # Optional — old payloads predate this field; renderers fall back
    # to deriving from decisions + open_questions.
    key_takeaways: list[str] = Field(default_factory=list)
    # Exactly 3 sentences that brief someone who didn't attend.
    # Distinct from `summary` (narrative prose) and `tldr` (one-glance
    # hook). Roles:
    #   [0] PURPOSE — the strategic frame / why this meeting existed
    #   [1] SUBSTANCE — what was actually discussed (concrete, not
    #       "Person A said X then B said Y" — synthesize)
    #   [2] LANDING — where it ended up: decision, open question, or
    #       next step. Honest when nothing resolved.
    # Rendered at the top of the Mind Map view. Empty when the model
    # couldn't produce a confident briefing (e.g. transcript too thin).
    briefing: list[str] = Field(default_factory=list)

    @field_validator("briefing", mode="before")
    @classmethod
    def _enforce_briefing_shape(cls, v):
        """Reject malformed briefings loudly. Only 0 (empty, valid
        fallback) or exactly 3 non-empty strings are accepted. Anything
        else — wrong length, non-string items, all-whitespace — gets
        coerced to [] with a warning so the Mind Map degrades to the
        legacy TL;DR card instead of rendering 2 sentences as if 3
        were intended.
        """
        if v in (None, [], ()):
            return []
        if not isinstance(v, list):
            logging.getLogger(__name__).warning(
                "briefing rejected: not a list (got %s)", type(v).__name__
            )
            return []
        clean = [s.strip() for s in v if isinstance(s, str) and s.strip()]
        if len(clean) != 3:
            logging.getLogger(__name__).warning(
                "briefing rejected: expected 3 non-empty strings, "
                "got %d (raw len=%d)",
                len(clean),
                len(v),
            )
            return []
        return clean
    # Second-pass narrative synthesis. None when the recap call failed
    # or the meeting had no decisions/actions/chapters to recap. The
    # field rides on atoms so persist_atoms can write it in the same
    # transaction; the LLM extraction itself never produces it (the
    # recap is a separate call against atoms-only input).
    executive_recap: ExecutiveRecap | None = None


@dataclass(frozen=True)
class TranscriptChunk:
    index: int
    text: str
    segment_ids: list[int]


def build_transcript_markdown(meeting_id: int, database_path) -> str:
    with connect(database_path) as conn:
        rows = conn.execute(
            """
            SELECT id, start_ms, end_ms, text, diarization_speaker_id
            FROM transcript_segments
            WHERE meeting_id = ?
            ORDER BY start_ms
            """,
            (meeting_id,),
        ).fetchall()
    lines = []
    for row in rows:
        timestamp = _format_timestamp(int(row["start_ms"]))
        text = safe_transcript_text(int(row["id"]), str(row["text"]))
        lines.append(
            f"- [{row['id']}] **{row['diarization_speaker_id']}** "
            f"[{timestamp}]: {text}"
        )
    return "\n".join(lines)


def chunk_transcript(config: AppConfig, meeting_id: int) -> list[TranscriptChunk]:
    with connect(config.paths.database_path) as conn:
        rows = conn.execute(
            """
            SELECT id, start_ms, text, diarization_speaker_id,
                   text_confidence, speaker_confidence, confidence
            FROM transcript_segments
            WHERE meeting_id = ?
            ORDER BY start_ms
            """,
            (meeting_id,),
        ).fetchall()
        # Resolve approved speaker labels so the LLM sees "Avery: ..." rather
        # than "Speaker 1: ...". Powers speaker-attributed summaries / actions.
        speaker_map = {
            row["diarization_speaker_id"]: row["approved_label"]
            for row in conn.execute(
                """
                SELECT diarization_speaker_id, approved_label
                FROM speaker_assignments
                WHERE meeting_id = ? AND approved_label IS NOT NULL
                """,
                (meeting_id,),
            ).fetchall()
            if row["approved_label"]
        }
        annotations = _review_annotations_by_segment(conn, meeting_id)

    chunks: list[TranscriptChunk] = []
    current: list[str] = []
    segment_ids: list[int] = []
    current_len = 0
    for row in rows:
        raw_speaker = row["diarization_speaker_id"]
        speaker = speaker_map.get(raw_speaker, raw_speaker)
        line = (
            f"[{row['id']}] {speaker} "
            f"{_format_timestamp(row['start_ms'])}: "
            f"{safe_transcript_text(int(row['id']), str(row['text']))}"
        )
        flags = _segment_extraction_flags(row, annotations.get(int(row["id"]), []))
        if flags:
            line = f"{line}\n  Review flags: {'; '.join(flags)}"
        if current and current_len + len(line) > config.chunking.target_chars:
            chunks.append(TranscriptChunk(len(chunks), "\n".join(current), list(segment_ids)))
            overlap_text = "\n".join(current)[-config.chunking.overlap_chars :]
            current = [overlap_text] if overlap_text else []
            segment_ids = segment_ids[-5:]
            current_len = len(overlap_text)
        current.append(line)
        segment_ids.append(int(row["id"]))
        current_len += len(line)
    if current:
        chunks.append(TranscriptChunk(len(chunks), "\n".join(current), list(segment_ids)))
    return chunks


TEMPLATE_PROMPTS: dict[str, str] = {
    "general": (
        "You are summarising a general business meeting. Extract concise "
        "structured meeting atoms as JSON. Preserve source segment ids.\n\n"
        "SPEAKER NAMING (applies to ALL prose fields — tldr, summary, "
        "decision.decision, decision.rationale, open_question fields, "
        "participant_contributions, chapter_markers.summary, tension "
        "sides, stat_callouts, anything readable): refer to participants "
        "by the EXACT name shown in the transcript. NEVER write 'Speaker "
        "N', 'Speaker 4', 'Speaker_002', or any placeholder. If the "
        "transcript itself uses a placeholder for a participant (e.g. "
        "'Speaker 2'), use the phrase 'a team member' or 'another "
        "participant' instead in your output prose — never echo the "
        "placeholder. Speaker placeholders in your output break reader "
        "trust and are a hard rule violation.\n\n"
        "Supply a `tldr` field: a single sentence (max 30 words) that "
        "answers 'if the reader sees nothing else, what happened in this "
        "meeting'. Outcome first, context second; never start with 'The "
        "meeting was…'. When a leading-context framing exists (e.g. "
        "'this is a compass check, not a final selection'), put that "
        "framing IN the tldr — the load-bearing context matters most. "
        "The fuller `summary` field should still capture "
        "the narrative; the tldr is the one-glance hook.\n\n"
        "Supply `briefing`: EXACTLY 3 sentences that brief a colleague "
        "who didn't attend. Each sentence has a specific role and order "
        "matters: "
        "[0] PURPOSE — the strategic frame (why this meeting existed, "
        "what stage of the work it sits in). Concrete (e.g. 'Architecture "
        "review of the payments service ahead of launch sign-off'), "
        "never generic ('Discussion of strategy'). "
        "[1] SUBSTANCE — what was actually discussed. SYNTHESIZE — do "
        "NOT write 'X said A, then Y said B'. Capture the through-line: "
        "the topics, numbers, names, or constraints the conversation "
        "actually moved between (e.g. 'Centered on two candidate vendors, "
        "with integration complexity and pricing flexibility as the main "
        "lenses'). "
        "[2] LANDING — where it ended up: a decision, an open question, "
        "a next step, or honest 'no commitments' when nothing resolved. "
        "Specific names and dates when stated. "
        "Each sentence max 35 words. Plain prose, no bullets. If the "
        "transcript is too thin to support 3 confident sentences, return "
        "an empty array — better blank than padded.\n\n"
        "Supply `key_takeaways`: 3 to 5 short bullet-style statements "
        "(each 12-30 words) that capture WHAT someone who wasn't in this "
        "meeting needs to know. Concrete: specific markets / numbers / "
        "names / decisions / thresholds / risks named in the transcript. "
        "Generic 'team aligned on strategy' bullets are forbidden — every "
        "takeaway must include a concrete object (a market, a number, a "
        "person, a constraint, a decision). Quote a phrase when it "
        "captures the substance. The audience is a peer reading the "
        "recap in an email; takeaways should be sharable as-is. "
        "Supply `themes`: 1-3 short two-word phrases (e.g. 'Strategic "
        "Analysis', 'Hiring Plan', 'Pricing Debate') that capture the lens "
        "of this specific meeting. Themes are different from workstreams "
        "— they're moods/angles for this conversation, not cross-meeting "
        "threads. Leave empty if the meeting was a single-topic chat. "
        "Supply `stat_callouts`: 0-3 numerical highlights worth pulling "
        "out as big stat cards. Pick durations, dollar amounts, "
        "percentages, ratios, or counts that carry real signal (e.g. "
        "value='16 to 1 weeks', label='Execution gap closed'). Use ASCII "
        "punctuation only (no fancy arrows or em-dashes inside value or "
        "label — they break in cross-platform exports). Skip incidental "
        "numbers like phone digits or meeting clock time. Each entry "
        "must cite source_segment_ids. Leave empty if no stat stands out. "
        "Supply `tension_points`: 0 entries is the right answer for most "
        "meetings (no tension = empty list). 1 entry only when the "
        "meeting actually had a real either/or (the parties disagreed, "
        "proposed competing approaches, or weighed a real trade-off). "
        "Do NOT invent tension to fill the field — synthetic positive/"
        "negative splits read as model hallucination and damage trust. "
        "Each entry: title, positive_side (1 sentence), negative_side "
        "(1 sentence). "
        "Supply `chapter_markers`: 4-8 time-anchored chapter labels that "
        "let a reader jump around the recording. Each label is at most 7 "
        "words, written like a section heading (e.g. 'Roadmap walkthrough', "
        "'Pricing model Q&A'). Set `start_segment_id` to the "
        "earliest source segment id where that chapter begins; chapters "
        "must be in chronological order and may not overlap. Add a one-"
        "sentence `summary` per chapter (12-25 words) that captures the "
        "concrete substance — what was actually discussed, decided, or "
        "disputed. Leave summary empty only when the chapter is genuinely "
        "too short for a useful one-sentence read. "
        "Supply `participant_contributions`: for each speaker who said "
        "anything substantive in this chunk, a 1-2 sentence distillation "
        "of what they brought — what they shared, what they asked, what "
        "they committed to. Use the speaker name exactly as it appears in "
        "the transcript (e.g. 'Jordan Reyes', not 'Speaker 4'). Skip "
        "speakers who only said acknowledgements or fillers. Aim for "
        "factual specifics: 'Jordan walked through the rollout plan, "
        "emphasising staged regional launches; asked Sam about "
        "the support escalation path' beats 'Jordan discussed launch topics'. "
        "Always propose 1 to 5 likely workstreams that a user should "
        "confirm, even when the transcript is ambiguous. For each "
        "workstream, supply a `description` that is exactly one sentence "
        "(12-25 words) capturing what was actually said about that thread "
        "— concrete, factual, avoid generic placeholders like 'discussion of X'. Treat lines "
        "marked with Review flags as lower-trust evidence: cite them only "
        "when useful, include uncertainty when they affect conclusions, and "
        "do not silently convert flagged content into facts. "
        "Supply `decisions`: each entry must include a `decision` (the "
        "outcome stated as a clear declarative, max 20 words) AND a "
        "`rationale` of one sentence (max 25 words) capturing WHY the "
        "decision was made — the trade-off considered, the constraint "
        "cited, the evidence that tipped the call. Only leave `rationale` "
        "null when the transcript truly contains no stated reasoning. "
        "Decisions without rationale rot fastest, so stretch to infer the "
        "rationale from the surrounding 60s of conversation when the "
        "speaker didn't say 'because' explicitly. "
        "Supply `open_questions` as structured objects: each entry has "
        "`question` (the question itself, max 25 words), `raised_by` (the "
        "speaker who asked, using the approved name from the transcript; "
        "null if unclear), `addressed_to` (the speaker the question was "
        "directed at, when explicit — null for broadcast questions), and "
        "`status` ∈ {unanswered, partially_answered, deferred}. Use "
        "`unanswered` when no on-topic response followed within ~90 seconds "
        "of transcript. Use `partially_answered` when a response came but "
        "didn't resolve the question (e.g. 'I'll look into it'). Use "
        "`deferred` when someone explicitly said 'let's come back to this' "
        "or 'park it'. Cite source_segment_ids of the question itself, not "
        "of the (missing) response. "
        "Action "
        "items: scan aggressively. Narrative-strong models tend to absorb "
        "commitments into prose and miss them. If anyone said 'I will…', "
        "'we should…', 'we'll send…', 'I'm going to…', 'let me follow up…', "
        "'we need to…', or named a future task in any tense — even as an "
        "aside, even mentioned in passing — treat it as an action item. "
        "Surveys to be sent, follow-up meetings to schedule, documents to "
        "circulate all count. Name the speaker who owns each action in the "
        "`owner` field whenever the transcript makes it clear — when an "
        "action is the speaker's own commitment ('I'll send the deck'), "
        "the owner is that speaker. Only leave `owner` null when the "
        "action is genuinely group-owned with no named individual. "
        "Parse explicit and relative due dates into the `due_date` field "
        "as YYYY-MM-DD. Resolve relative phrases ('by Friday', 'next "
        "week', 'end of month', 'EOD', 'tomorrow') against the meeting "
        "date supplied in Meeting Context below. When a phrase is "
        "genuinely ambiguous ('soon', 'eventually', 'when ready'), leave "
        "`due_date` null. When you do set a due_date, set "
        "`due_date_source` to the segment id where the date phrase was "
        "stated so the reader can verify. Better to "
        "surface a borderline action than miss a real one. When "
        "segments have Review flags, low speaker confidence, or names that "
        "look like ASR mishears (e.g. a person referenced once with a "
        "phonetically odd spelling), add a short note in uncertainties "
        "calling out which segment ids you are less sure about and why. "
        "Prefer listing two or three concrete uncertainties over an empty "
        "list whenever transcript quality is imperfect."
    ),
    "standup": (
        "You are summarising a team standup. Each contributor reports what "
        "they did, what they will do, and what is blocking them. Extract "
        "atoms as JSON: prefer many short actions (one per contributor) over "
        "long narrative summaries; treat blockers as open_questions; treat "
        "the recurring themes that show up across multiple speakers as "
        "workstreams. Owners on actions are the speaker who said it. "
        "Preserve source segment ids."
    ),
    "one_on_one": (
        "You are summarising a 1:1 between two people. Treat shared topics "
        "as workstreams; treat coaching or feedback statements as decisions "
        "only when the parties explicitly agreed. Actions belong to whichever "
        "speaker accepted them. Open questions cover items raised but not "
        "resolved. Preserve source segment ids."
    ),
    "customer_interview": (
        "You are summarising a customer or user interview. Workstreams are "
        "the product surfaces or use cases the customer touched. Decisions "
        "are explicit yes/no statements from the customer. Actions are "
        "internal follow-ups the interviewer agreed to take. Quotes and "
        "verbatim pain points belong in open_questions when they need "
        "follow-up, otherwise in uncertainties. Preserve source segment ids."
    ),
}


def _template_for_meeting(config: AppConfig, meeting_id: int) -> str:
    with connect(config.paths.database_path) as conn:
        row = conn.execute(
            "SELECT template FROM meetings WHERE id = ?", (meeting_id,)
        ).fetchone()
    template = (row["template"] if row and row["template"] else "general")
    return template if template in TEMPLATE_PROMPTS else "general"


def _meeting_date_iso(config: AppConfig, meeting_id: int) -> str | None:
    """Return the meeting's date as YYYY-MM-DD for relative-date resolution.

    Reads `meetings.created_at` (SQLite CURRENT_TIMESTAMP, e.g.
    '2026-05-15 18:34:21' or an ISO 'YYYY-MM-DDTHH:MM:SS' from Python).
    Returns None if the row is missing or unparseable — caller proceeds
    without the date hint rather than failing extraction.
    """
    with connect(config.paths.database_path) as conn:
        row = conn.execute(
            "SELECT created_at FROM meetings WHERE id = ?", (meeting_id,)
        ).fetchone()
    if not row or not row["created_at"]:
        return None
    raw = str(row["created_at"]).strip()
    if len(raw) < 10:
        return None
    candidate = raw[:10]
    if re.match(r"^\d{4}-\d{2}-\d{2}$", candidate):
        return candidate
    return None


def _precompute_downstream_caches(config: AppConfig, meeting_id: int) -> None:
    """Warm the per-meeting LLM caches that the dashboard would otherwise
    hit cold on first open.

    Fires drivers (which triggers enrichment internally), key_terms, and
    reflections concurrently against the worktree's ThreadPoolExecutor.
    Each callee writes its own meeting_*_cache row on success; failures
    are logged and swallowed so a partial precompute doesn't block the
    extract step from completing.

    Reflections only runs when an owner is configured AND skip_reflections
    isn't set on the meeting — otherwise the underlying service short-
    circuits before any LLM call, so the precompute cost is zero.
    """
    from concurrent.futures import ThreadPoolExecutor

    from app.services.conversation_drivers import compute_drivers_and_cog
    from app.services.reflections import compute_reflections
    from app.services.synthesis import build_synthesis_snapshot

    def _safe(name: str, fn):
        try:
            fn()
        except Exception as exc:  # noqa: BLE001 — precompute is best-effort
            LOGGER.warning(
                "precompute_failed meeting_id=%s task=%s err=%s",
                meeting_id, name, exc,
            )

    with ThreadPoolExecutor(max_workers=3) as executor:
        executor.submit(_safe, "drivers", lambda: compute_drivers_and_cog(config, meeting_id))
        executor.submit(_safe, "key_terms", lambda: build_synthesis_snapshot(config, meeting_id))
        executor.submit(_safe, "reflections", lambda: compute_reflections(config, meeting_id))


def extract_meeting_atoms(config: AppConfig, meeting_id: int) -> MeetingAtoms:
    from app.services.driver_enrichment import invalidate_driver_enrichment_cache
    from app.services.llm_drivers import invalidate_llm_drivers_cache
    from app.services.pipeline import _emit_progress
    from app.services.reflections import invalidate_reflections_cache
    from app.services.synthesis import invalidate_key_terms_cache

    _emit_progress(config, meeting_id, "extract", "running", 0.0)
    # Re-extracting changes the source content the cached LLM passes
    # operated over; drop all dependent caches so the next dashboard
    # load recomputes against the fresh transcript / atoms.
    invalidate_key_terms_cache(config, meeting_id)
    invalidate_llm_drivers_cache(config, meeting_id)
    invalidate_driver_enrichment_cache(config, meeting_id)
    invalidate_reflections_cache(config, meeting_id)
    chunks = chunk_transcript(config, meeting_id)
    if not chunks:
        _emit_progress(config, meeting_id, "extract", "complete", 1.0)
        return MeetingAtoms(
            suggested_title="Untitled Meeting",
            tldr="No transcript available.",
            summary="No transcript available.",
        )

    model_bus = ModelBus(config)
    partials: list[MeetingAtoms] = []
    schema = MeetingAtoms.model_json_schema()
    template = _template_for_meeting(config, meeting_id)
    # Append a "Meeting Context" block so the model can resolve relative
    # due dates ("by Friday") to absolute YYYY-MM-DD on the model side
    # rather than us doing brittle string parsing on the backend. Skipped
    # silently when created_at is missing or unparseable.
    meeting_date = _meeting_date_iso(config, meeting_id)
    system_prompt = TEMPLATE_PROMPTS[template]
    if meeting_date:
        system_prompt = (
            f"{system_prompt}\n\nMeeting Context: this meeting took place "
            f"on {meeting_date}. Resolve relative date phrases against "
            "this date."
        )
    total = max(1, len(chunks))
    # v0.2.6: thread quality hints from the v0.2.2 overlap detector and
    # v0.2.4 speaker reattributer into each chunk's user message. The
    # synthesis LLM is told to hedge attribution on flagged segments
    # rather than confidently quoting a speaker whose label is suspect.
    from app.services.repair.quality_hints import augmented_chunk_text

    for index, chunk in enumerate(chunks, start=1):
        augmented_user_text = augmented_chunk_text(
            config, meeting_id, chunk.text, chunk.segment_ids
        )
        payload = model_bus.chat_json(
            [
                ChatMessage("system", system_prompt),
                ChatMessage("user", augmented_user_text),
            ],
            {"name": "MeetingAtoms", "schema": schema},
        )
        partials.append(MeetingAtoms.model_validate(payload))
        # Stop short of 0.85 so the consolidation + persist tail has room.
        _emit_progress(
            config, meeting_id,
            "extract",
            "running",
            0.05 + 0.75 * (index / total),
        )

    # Use the first non-empty tldr — the opening chunk best captures "what
    # this meeting is about" since context flows forward. Per-chunk tldrs
    # from later chunks would describe sub-segments, not the whole.
    chunk_tldr = next((part.tldr.strip() for part in partials if part.tldr.strip()), "")
    # For `briefing`, take the LAST chunk that produced a complete
    # 3-sentence briefing. The LANDING sentence (briefing[2]) requires
    # the model to see how the meeting ended — first-chunk bias would
    # report an agenda-setting "no commitments" even when the meeting
    # later landed a decision. PURPOSE drift from late chunks is
    # acceptable; LANDING accuracy matters more. Field validator on
    # MeetingAtoms.briefing already enforces "exactly 3 non-empty
    # strings or empty list" so the partials we consider are already
    # well-formed.
    chunk_briefing: list[str] = next(
        (
            list(part.briefing)
            for part in reversed(partials)
            if len(part.briefing) == 3
        ),
        [],
    )
    merged = MeetingAtoms(
        suggested_title=partials[0].suggested_title,
        tldr=chunk_tldr,
        summary="\n".join(part.summary for part in partials if part.summary),
        actions=[action for part in partials for action in part.actions],
        decisions=[decision for part in partials for decision in part.decisions],
        workstreams=[workstream for part in partials for workstream in part.workstreams],
        participant_contributions=_merge_participant_contributions(partials),
        chapter_markers=_merge_chapter_markers(partials),
        themes=_merge_themes(partials),
        stat_callouts=_merge_stat_callouts(partials),
        tension_points=_merge_tension_points(partials),
        open_questions=_dedupe_open_questions(
            [question for part in partials for question in part.open_questions]
        ),
        uncertainties=[uncertainty for part in partials for uncertainty in part.uncertainties],
        key_takeaways=_merge_key_takeaways(partials),
        briefing=chunk_briefing,
    )
    # When a long transcript produced overlapping workstreams across chunks,
    # ask the model to consolidate semantic duplicates (e.g. "Marketing
    # Strategy" + "Strategy Marketing") into a deduplicated, ranked list.
    # Workstream consolidation: tighter trigger (>3 instead of >4) so
    # meetings with 4-5 near-duplicate workstreams (e.g. three labels
    # that all describe the same strategic thread) get consolidated
    # too. Long transcripts that yield 7+ workstreams almost always
    # have heavy overlap; the prior >4 threshold under-deduped them.
    if len(merged.workstreams) > 3:
        _emit_progress(config, meeting_id, "extract", "running", 0.88)
        merged.workstreams = _consolidate_workstreams(model_bus, merged.workstreams)
    # Synthesize the executive recap before persisting so persist_atoms
    # can store the recap alongside the atoms in a single transaction.
    # Failures here are silent: the dashboard falls back to the existing
    # summary field if the recap is missing.
    _emit_progress(config, meeting_id, "extract", "running", 0.92)
    merged.executive_recap = synthesize_executive_recap(model_bus, merged)
    _emit_progress(config, meeting_id, "extract", "running", 0.94)
    persist_atoms(config, meeting_id, merged)
    # Precompute downstream caches in parallel so the first dashboard
    # open after extract is instant. Each of these would otherwise fire
    # on the GET /api/meetings/{id} cold path (drivers ~60s, enrichment
    # ~30s, key_terms ~30s, reflections ~30s on OpenRouter). Running
    # them now — while the user is already waiting on `mm extract` —
    # moves the latency to a moment the user expects to wait, and the
    # ThreadPoolExecutor halves wall-clock by running independent calls
    # concurrently. Failures here are non-fatal: they log a warning and
    # the dashboard's cache-miss path picks them up later.
    _emit_progress(config, meeting_id, "extract", "running", 0.96)
    _precompute_downstream_caches(config, meeting_id)
    # Auto-send to Obsidian if the user opted in AND speaker review is
    # already complete (every distinct diarization speaker has a
    # user-confirmed assignment). Only fires when the vault dir exists;
    # otherwise the silent no-op would mask the missing-Obsidian
    # condition.
    if config.dashboard.auto_send_to_obsidian and config.paths.vault_dir.exists():
        try:
            with connect(config.paths.database_path) as _conn:
                total = _conn.execute(
                    "SELECT COUNT(DISTINCT diarization_speaker_id) "
                    "FROM transcript_segments WHERE meeting_id = ?",
                    (meeting_id,),
                ).fetchone()[0]
                confirmed = _conn.execute(
                    "SELECT COUNT(*) FROM speaker_assignments "
                    "WHERE meeting_id = ? AND confirmed_by_user = 1",
                    (meeting_id,),
                ).fetchone()[0]
            speakers_done = total > 0 and confirmed >= total
            if speakers_done:
                from app.services.obsidian_writer import promote_meeting

                promote_meeting(config, meeting_id)
                LOGGER.info("auto_promoted meeting_id=%s", meeting_id)
        except Exception as exc:  # noqa: BLE001 — auto-promote must not block extract
            LOGGER.warning("auto_promote_failed meeting_id=%s err=%s", meeting_id, exc)
    _emit_progress(config, meeting_id, "extract", "complete", 1.0)
    return merged


# Action-clustering token-stripping set. Stopwords proper plus action-verb
# noise that drowns out the real signal in short task strings: "send the
# deck" and "share the deck" should cluster on `deck`, not be pulled apart
# by "send" vs "share".
_ACTION_STOP_TOKENS = frozenset({
    "the", "a", "an", "is", "are", "do", "does", "did", "will", "would",
    "could", "should", "in", "on", "at", "to", "for", "of", "and", "or",
    "we", "you", "this", "that", "be", "by", "with", "from", "into", "onto",
    "send", "share", "give", "make", "get", "ill", "im", "have", "has", "had",
    "let", "lets", "want", "need", "going", "gonna", "team", "her",
    "him", "his", "their", "them", "they", "out", "up", "after", "before",
})


def _action_tokens(text: str) -> set[str]:
    return {
        w
        for w in re.findall(r"[a-z0-9]+", text.lower())
        if len(w) > 2 and w not in _ACTION_STOP_TOKENS
    }


def _cluster_actions(
    actions: list[ExtractedAction],
    owner_ids: list[int | None],
) -> list[list[int]]:
    """Group near-duplicate actions into clusters.

    Returns a list of clusters, each a list of indices into `actions` in
    original order. Standalone actions appear as single-item lists. The
    first index in each cluster is the canonical (most specific phrasing).

    Heuristic — token Jaccard ≥ 0.55 AND (same owner OR ≥1 shared source
    segment). The owner-or-segment gate stops over-merging across
    complementary commitments by different speakers ("you connect us" /
    "I'll share notes" share the segment but different owners → keep
    apart; "send the deck" / "circulate the slides" share the owner →
    merge).
    """
    n = len(actions)
    if n <= 1:
        return [[i] for i in range(n)]

    tokens = [_action_tokens(a.task) for a in actions]
    seg_sets = [set(a.source_segment_ids) for a in actions]
    cluster_of: list[int] = list(range(n))  # each starts in its own cluster

    for i in range(n):
        if not tokens[i]:
            continue
        for j in range(i):
            if cluster_of[j] != j:
                continue  # only compare against existing cluster heads
            if not tokens[j]:
                continue
            inter = len(tokens[i] & tokens[j])
            union = len(tokens[i] | tokens[j])
            if union == 0:
                continue
            jaccard = inter / union
            if jaccard < 0.55:
                continue
            same_owner = (
                owner_ids[i] is not None
                and owner_ids[j] is not None
                and owner_ids[i] == owner_ids[j]
            )
            shared_seg = bool(seg_sets[i] & seg_sets[j])
            if same_owner or shared_seg:
                cluster_of[i] = cluster_of[j]
                break

    groups: dict[int, list[int]] = {}
    for idx, head in enumerate(cluster_of):
        groups.setdefault(head, []).append(idx)

    # Canonical = highest priority, then longest text, then earliest
    # segment. The canonical is what the UI shows by default; members
    # back it with evidence.
    priority_rank = {"high": 0, "normal": 1, "low": 2}

    def _canonical_key(idx: int) -> tuple[int, int, int]:
        a = actions[idx]
        longest_neg = -len(a.task or "")
        earliest = min(a.source_segment_ids) if a.source_segment_ids else 10**9
        return (priority_rank.get(a.priority, 1), longest_neg, earliest)

    out: list[list[int]] = []
    for head in sorted(groups):
        members = groups[head]
        if len(members) > 1:
            members.sort(key=_canonical_key)
        out.append(members)
    return out


def _resolve_cluster_due_date(
    members: list[ExtractedAction],
) -> tuple[str | None, int | None, list[dict[str, object]]]:
    """Pick the cluster's due date from member commitments.

    Rule: among members with a non-null `due_date`, the one mentioned in
    the latest source segment wins. Undated paraphrases don't overwrite a
    real earlier commitment. If two members carry different non-null
    dates, the chronologically later mention wins but `history` records
    the prior commitments so the UI can show "Tue (was Fri earlier)".
    """
    dated = [
        (
            max(a.source_segment_ids) if a.source_segment_ids else -1,
            a.due_date,
            a.due_date_source,
        )
        for a in members
        if a.due_date
    ]
    if not dated:
        return None, None, []
    # Sort by latest segment first, breaking ties on the date string
    # itself so the result is fully deterministic when two members share
    # the same `max(source_segment_ids)`. ISO-8601 dates sort
    # chronologically as plain strings, so the later calendar date wins
    # on a same-segment tie.
    dated.sort(key=lambda t: (t[0], t[1] or ""))
    latest = dated[-1]
    history = [
        {"date": d, "segment_id": seg if seg > -1 else None}
        for seg, d, _ in dated[:-1]
        if d != latest[1]
    ]
    return latest[1], latest[2], history


def _dedupe_open_questions(
    questions: list[ExtractedOpenQuestion],
) -> list[ExtractedOpenQuestion]:
    """Cheap semantic dedup on open questions.

    Frontier and local models alike emit near-duplicate questions when a
    transcript repeats a topic across chunks. Example seen in the wild:
    "Can the team build a referral pool of 20 patients per month within
    three months?" and "Can the team build a referral pool of 20
    patients per month within three months in Minneapolis?" — same
    question with slightly different scope. We keep the longer / more
    specific phrasing and merge source_segment_ids.

    Heuristic (no LLM call): token-set Jaccard similarity on the
    lowercase tokens, ignoring stopwords. Pairs above the threshold
    are considered duplicates and merged into the longer one. Order
    is preserved (first occurrence wins for the "earliest segment"
    sort key downstream).
    """
    if len(questions) <= 1:
        return list(questions)

    def tokens(text: str) -> set[str]:
        stop = {
            "the", "a", "an", "is", "are", "do", "does", "did", "will",
            "would", "could", "should", "in", "on", "at", "to", "for",
            "of", "and", "or", "we", "you", "this", "that", "be", "by",
        }
        words = re.findall(r"[a-z0-9]+", text.lower())
        return {w for w in words if len(w) > 2 and w not in stop}

    kept: list[ExtractedOpenQuestion] = []
    kept_tokens: list[set[str]] = []
    for q in questions:
        t = tokens(q.question)
        if not t:
            kept.append(q)
            kept_tokens.append(t)
            continue
        merged = False
        for i, kt in enumerate(kept_tokens):
            if not kt:
                continue
            inter = len(t & kt)
            union = len(t | kt)
            jaccard = inter / union if union else 0
            # 0.75 threshold catches the Minneapolis duplicate (token
            # sets overlap heavily) without over-merging genuinely
            # distinct questions (which typically share <0.4 of tokens).
            if jaccard >= 0.75:
                # Prefer the longer / more specific phrasing; merge
                # source_segment_ids so evidence pills carry both
                # citations.
                if len(q.question) > len(kept[i].question):
                    seg_ids = list(
                        dict.fromkeys(
                            kept[i].source_segment_ids + q.source_segment_ids
                        )
                    )
                    kept[i] = q.model_copy(update={"source_segment_ids": seg_ids})
                    kept_tokens[i] = t
                else:
                    seg_ids = list(
                        dict.fromkeys(
                            kept[i].source_segment_ids + q.source_segment_ids
                        )
                    )
                    kept[i] = kept[i].model_copy(update={"source_segment_ids": seg_ids})
                merged = True
                break
        if not merged:
            kept.append(q)
            kept_tokens.append(t)
    return kept


def _merge_key_takeaways(partials: list[MeetingAtoms]) -> list[str]:
    """De-duplicate key_takeaways across chunks (case-insensitive
    prefix match — chunks tend to repeat the same takeaway with minor
    wording differences). Cap at 5; the first non-empty wording wins.
    """
    seen: list[str] = []
    out: list[str] = []
    for part in partials:
        for raw in part.key_takeaways:
            clean = (raw or "").strip().rstrip(".") + "."
            if not clean or clean == ".":
                continue
            head_full = clean.casefold()
            head_key = head_full[:30]
            # Match on shared 30-char opening (or full string when shorter)
            # so two takeaways that differ only in suffix dedupe correctly.
            # Bug-fix: previously compared seen-entries' .startswith(head[:30])
            # which fails for stored entries shorter than 30 chars.
            if any(s[:30] == head_key for s in seen):
                continue
            seen.append(head_full)
            out.append(clean)
            if len(out) >= 5:
                return out
    return out


def _merge_themes(partials: list[MeetingAtoms]) -> list[str]:
    """Dedupe theme strings across chunks (case-insensitive), cap at 3.

    Themes are the same across the meeting — chunks usually repeat them.
    """
    seen: set[str] = set()
    out: list[str] = []
    for part in partials:
        for raw in part.themes:
            clean = (raw or "").strip()
            if not clean or clean.casefold() in seen:
                continue
            seen.add(clean.casefold())
            out.append(clean)
            if len(out) >= 3:
                return out
    return out


def _merge_stat_callouts(partials: list[MeetingAtoms]) -> list[StatCallout]:
    """De-duplicate stat callouts by label (case-insensitive). Keep at
    most 3. Earlier chunks win — they tend to capture the framing
    statistics; later chunks repeat or add tactical numbers.
    """
    seen: set[str] = set()
    out: list[StatCallout] = []
    for part in partials:
        for entry in part.stat_callouts:
            label = (entry.label or "").strip()
            value = (entry.value or "").strip()
            if not label or not value:
                continue
            key = label.casefold()
            if key in seen:
                continue
            seen.add(key)
            out.append(
                StatCallout(
                    value=value[:60],
                    label=label[:80],
                    source_segment_ids=list(entry.source_segment_ids),
                )
            )
            if len(out) >= 3:
                return out
    return out


def _merge_tension_points(partials: list[MeetingAtoms]) -> list[TensionPoint]:
    """De-duplicate tension points by title (case-insensitive). Keep at
    most 2; tension is rare and most meetings produce 0-1.
    """
    seen: set[str] = set()
    out: list[TensionPoint] = []
    for part in partials:
        for entry in part.tension_points:
            title = (entry.title or "").strip()
            pos = (entry.positive_side or "").strip()
            neg = (entry.negative_side or "").strip()
            if not title or not (pos or neg):
                continue
            key = title.casefold()
            if key in seen:
                continue
            seen.add(key)
            out.append(
                TensionPoint(
                    title=title[:120],
                    positive_side=pos[:280],
                    negative_side=neg[:280],
                    source_segment_ids=list(entry.source_segment_ids),
                )
            )
            if len(out) >= 2:
                return out
    return out


def _merge_chapter_markers(partials: list[MeetingAtoms]) -> list[ChapterMarker]:
    """Combine per-chunk chapter lists into a single chronological set.

    Sort by start_segment_id, drop duplicates (within 4 segment-ids of a
    previous one), cap label at 7 words, and limit to 12 chapters total
    so the rail stays scannable on long meetings.
    """
    raw = [chapter for part in partials for chapter in part.chapter_markers]
    raw.sort(key=lambda chapter: chapter.start_segment_id)
    out: list[ChapterMarker] = []
    for chapter in raw:
        label = " ".join((chapter.label or "").strip().split())
        words = label.split(" ")
        if len(words) > 7:
            label = " ".join(words[:7])
        if not label:
            continue
        if out and abs(chapter.start_segment_id - out[-1].start_segment_id) < 4:
            continue
        out.append(ChapterMarker(label=label, start_segment_id=chapter.start_segment_id))
        if len(out) >= 12:
            break
    return out


def _merge_participant_contributions(
    partials: list[MeetingAtoms],
) -> list[ParticipantContribution]:
    """Combine per-chunk contribution lists into one per-speaker entry.

    A given speaker may appear in multiple chunks; we concatenate their
    contribution sentences with " · " separators and de-duplicate by
    case-insensitive speaker name. Source segment ids are pooled.
    """
    by_speaker: dict[str, dict] = {}
    for part in partials:
        for entry in part.participant_contributions:
            name = entry.speaker.strip()
            if not name or not entry.contribution.strip():
                continue
            key = name.casefold()
            bucket = by_speaker.setdefault(
                key,
                {"speaker": name, "lines": [], "segments": []},
            )
            text = entry.contribution.strip()
            # Avoid identical-string duplication when later chunks repeat
            # the same observation about a speaker.
            if not any(line.casefold() == text.casefold() for line in bucket["lines"]):
                bucket["lines"].append(text)
            bucket["segments"].extend(entry.source_segment_ids)
    return [
        ParticipantContribution(
            speaker=data["speaker"],
            contribution=" · ".join(data["lines"]),
            source_segment_ids=list(dict.fromkeys(data["segments"])),
        )
        for data in by_speaker.values()
    ]


def _coerce_int_id(value) -> int | None:
    """Accept either int or integer-valued float / numeric string ids."""
    try:
        if isinstance(value, bool):  # bool is a subclass of int in Python
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float) and value.is_integer():
            return int(value)
        if isinstance(value, str) and value.strip().lstrip("-").isdigit():
            return int(value)
    except (TypeError, ValueError):
        return None
    return None


_EXEC_RECAP_PROMPT = """\
You are writing an executive recap of a meeting based on its already-
extracted structured atoms. NEVER read raw transcript text — work only
from the atoms below. Every claim in your recap must trace to a
decision, action, chapter_marker, tension_point, or theme.

OUTPUT FORMAT — return JSON matching the schema you've been given. \
Total word count across all body strings: 180-240 words. Bullets are \
NOT counted against the budget. Going over 240 means cut adjectives, \
not facts.

═══════════════════════════════════════════════════════════════════
SECTION RULES — voice differs per section. Read carefully.
═══════════════════════════════════════════════════════════════════

REFRAME section:
  Find the pivotal moment the meeting's frame changed — a reframe, a
  pivot, a constraint surfacing, a decision direction flipping.
  Anchor to a specific person and a specific cognitive move (what they
  saw that others didn't, what shifted because of it).

  HEADER: write with editorial confidence. Name the shift, not the
  topic. Good: "Sam saw a sequencing trap, not a sequencing problem."
  Bad: "Discussion of Q3 roadmap." Headers are claims, not labels.

  BODY: explain HOW the reframe worked mechanically. What did the
  person see? What followed from it? Use one short italicised
  paraphrase of the pivotal claim if it lands cleanly (max one
  italics per recap). Bold the load-bearing numbers/dates/names.

  FALLBACK: if no clear reframe exists (status meeting, routine
  standup), title this section "The meeting in one move" and
  summarise the meeting's main thread in declarative voice. Do not
  invent a reframe.

STRATEGY section:
  Re-organise the meeting's commitments as a single coordinated plan,
  not a task list. The body sentence sets up the bullets by naming
  the through-line ("expand QA throughput," "de-risk the launch,"
  "harden the customer story").

  HEADER: editorial. Good: "Every commitment serves the new strategy."
  / "The plan splits across three fronts." Bad: "Action items" /
  "Next steps." Headers earn the read.

  BULLETS: one per owned action from the atoms. Owners come from
  action.owner. The `purpose` clause is one short phrase tying the
  commitment to the strategy — derive it from action context,
  rationale fields, or chapter summaries. Examples: "fastest path
  to a posted req", "parallel pipeline", "buys time", "ready to
  consume new capacity".

  PURPOSE FALLBACK: if you can't honestly tie a commitment to the
  through-line, use purpose: null. Do NOT fabricate strategic
  purposes — bare bullets are better than dishonest ones.

  TRAILER: include only if something substantive was deferred,
  parked, or explicitly scoped OUT of this meeting. Null otherwise.

  STRATEGY FALLBACK: if commitments don't share a through-line at
  all, title this section "Commitments leaving the room", write a
  one-sentence body, and emit bullets with purpose: null.

RISK section:
  Identify the load-bearing assumption the plan rests on — the single
  thing that, if it breaks, breaks the rest. Derive this from
  dependency chains in the actions.

  HEADER: conservative and neutral. Good: "Open risk" / "Load-bearing
  assumption" / "Where this plan is thin." Bad: "One risk nobody
  elevated" / "The unspoken risk." Editorial confidence does NOT
  belong here — risk-naming is inference from absence.

  BODY: name the assumption, name what slips if it breaks, then end
  with one factual sentence about whether the meeting addressed it.
  Allowed: "This risk was not explicitly discussed in the meeting."
  / "The meeting did not establish a contingency." Banned: "Nobody
  named this out loud" / any phrasing that editorialises the silence.

  RISK FALLBACK: if no clear load-bearing assumption exists, return
  header: null, body: null. Better to skip than to invent a risk.

═══════════════════════════════════════════════════════════════════
GLOBAL RULES
═══════════════════════════════════════════════════════════════════

- NEVER write "the team aligned" or "everyone agreed" — name specific
  people who pushed and specific people who accepted.
- NEVER quote the transcript directly. Paraphrase. You don't have the
  transcript, only atoms.
- NEVER invent atoms. If a decision/action/risk isn't in the inputs,
  it doesn't exist for the recap.
- Bold (**text**) is reserved for load-bearing numbers, dates, and
  names — the things a skeptical reader would verify. Max ~5 bolded
  spans per recap.
- Italics (*text*) is reserved for ONE paraphrase of the pivotal
  claim in the reframe section. Zero or one usage per recap.
- People are referenced by their first-name display label as it
  appears in actions[].owner and decisions[].decision. Never
  "Speaker 1" / "a participant" / placeholders.
"""


_EXEC_RECAP_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "reframe": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "header": {"type": ["string", "null"]},
                "body": {"type": ["string", "null"]},
            },
            "required": ["header", "body"],
        },
        "strategy": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "header": {"type": ["string", "null"]},
                "body": {"type": ["string", "null"]},
                "bullets": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "owner": {"type": "string"},
                            "commitment": {"type": "string"},
                            "purpose": {"type": ["string", "null"]},
                        },
                        "required": ["owner", "commitment"],
                    },
                },
                "trailer": {"type": ["string", "null"]},
            },
            "required": ["header", "body", "bullets"],
        },
        "risk": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "header": {"type": ["string", "null"]},
                "body": {"type": ["string", "null"]},
            },
            "required": ["header", "body"],
        },
    },
    "required": ["reframe", "strategy", "risk"],
}


def synthesize_executive_recap(
    model_bus: ModelBus, atoms: MeetingAtoms
) -> ExecutiveRecap | None:
    """Second-pass narrative synthesis from atoms.

    Reads only the structured atoms (no transcript) and produces a
    three-section Plaud-style executive recap. Returns None on any
    failure so the dashboard falls back to the existing summary
    field — synthesis is enrichment, not a hard dependency.
    """
    # Skeleton input: keep the prompt focused on what shape the model
    # needs, not on transport. Only fields the recap actually uses are
    # serialized; everything else is dropped to keep the prompt cheap.
    inputs = {
        "themes": atoms.themes,
        "decisions": [
            {
                "decision": d.decision,
                "rationale": d.rationale,
            }
            for d in atoms.decisions
        ],
        "tension_points": [
            {
                "title": t.title,
                "positive_side": t.positive_side,
                "negative_side": t.negative_side,
            }
            for t in atoms.tension_points
        ],
        "chapter_markers": [
            {
                "title": c.label,
                "summary": c.summary,
                "start_segment_id": c.start_segment_id,
            }
            for c in atoms.chapter_markers
        ],
        "actions": [
            {
                "owner": a.owner,
                "task": a.task,
                "due_date": a.due_date,
                "priority": a.priority,
            }
            for a in atoms.actions
        ],
        "key_takeaways": atoms.key_takeaways,
        "participant_contributions": [
            {
                "speaker": p.speaker,
                "summary": p.contribution,
            }
            for p in atoms.participant_contributions
        ],
    }
    if not (atoms.decisions or atoms.actions or atoms.chapter_markers):
        # Nothing substantive to recap — let the dashboard fall back.
        return None
    try:
        payload = model_bus.chat_json(
            [
                ChatMessage("system", _EXEC_RECAP_PROMPT),
                ChatMessage("user", json.dumps(inputs)),
            ],
            {"name": "ExecutiveRecap", "schema": _EXEC_RECAP_SCHEMA},
            # Editorial-voice synthesis needs the stronger model; the
            # default cheap model produces bland headers.
            model=model_bus.config.models.quality_model,
            timeout=45,
        )
        if not isinstance(payload, dict):
            return None
        return ExecutiveRecap.model_validate(payload)
    except Exception as exc:  # noqa: BLE001 — recap is best-effort
        LOGGER.warning("synthesize_executive_recap_failed err=%s", exc)
        return None


def _consolidate_workstreams(
    model_bus: ModelBus, workstreams: list[ExtractedWorkstream]
) -> list[ExtractedWorkstream]:
    """Second LLM pass to merge near-duplicate workstreams produced by per-chunk
    extraction. Falls back to the input list on any failure so the pipeline
    stays reliable.
    """
    if not workstreams:
        return workstreams
    candidates_json = json.dumps(
        [
            {
                "name": w.name,
                "description": w.description,
                "confidence": w.confidence,
                "source_segment_ids": w.source_segment_ids,
            }
            for w in workstreams
        ]
    )
    schema = {
        "type": "object",
        "properties": {
            "workstreams": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "description": {"type": "string"},
                        "confidence": {"type": "number"},
                        "source_segment_ids": {"type": "array", "items": {"type": "integer"}},
                    },
                    "required": ["name"],
                },
                "maxItems": 8,
            }
        },
        "required": ["workstreams"],
    }
    try:
        payload = model_bus.chat_json(
            [
                ChatMessage(
                    "system",
                    "You consolidate candidate meeting workstreams aggressively. "
                    "Merge any items that overlap semantically — different "
                    "wording of the same thread is the common pattern. "
                    "Example to MERGE: 'Roadmap Planning', 'Q3 Priorities', "
                    "'Launch Sequencing', 'Release Timeline' are four labels "
                    "for one thread about what ships when — collapse into a "
                    "single 'Roadmap and release sequencing' workstream. "
                    "Only merge when items refer to the SAME decisions and "
                    "actors; keep multiple workstreams when they are clearly "
                    "distinct lanes of work (e.g. 'Hiring' and 'Roadmap "
                    "Planning' are distinct lanes; 'Roadmap Planning' and "
                    "'Launch Sequencing' are the same lane). "
                    "Keep the clearest name; merge descriptions into one "
                    "concrete one-sentence summary (12-25 words) of what was "
                    "said about that thread; sum source_segment_ids; take "
                    "the max confidence. Drop generic catch-alls like "
                    "'general discussion'. Return 3 to 5 workstreams ranked "
                    "by confidence. Fewer-is-better here — better one "
                    "honest workstream than three nominally-distinct labels "
                    "for the same thing.",
                ),
                ChatMessage("user", candidates_json),
            ],
            {"name": "ConsolidatedWorkstreams", "schema": schema},
            # The quality model is more reliable at semantic merging than
            # the default; this single call decides what surfaces in the UI.
            model=model_bus.config.models.quality_model,
            # Secondary call — fail fast and keep the unconsolidated list
            # rather than hang the synthesis pass.
            timeout=45,
        )
        result = payload.get("workstreams") if isinstance(payload, dict) else None
        if isinstance(result, list) and result:
            consolidated: list[ExtractedWorkstream] = []
            for item in result:
                if not isinstance(item, dict):
                    continue
                name = str(item.get("name") or "").strip()
                if not name:
                    continue
                description = str(item.get("description") or "").strip()
                confidence_raw = item.get("confidence")
                try:
                    confidence = float(confidence_raw) if confidence_raw is not None else 0.5
                except (TypeError, ValueError):
                    confidence = 0.5
                segment_ids: list[int] = []
                for sid in item.get("source_segment_ids") or []:
                    coerced = _coerce_int_id(sid)
                    if coerced is not None:
                        segment_ids.append(coerced)
                consolidated.append(
                    ExtractedWorkstream(
                        name=name[:120],
                        description=description[:320],
                        confidence=max(0.0, min(1.0, confidence)),
                        source_segment_ids=segment_ids,
                    )
                )
            if consolidated:
                return consolidated
    except Exception as exc:  # noqa: BLE001 — best-effort consolidation
        LOGGER.warning("consolidate_workstreams_failed err=%s", exc)
        return workstreams
    return workstreams


def regenerate_meeting_synthesis(config: AppConfig, meeting_id: int) -> MeetingAtoms:
    with connect(config.paths.database_path) as conn:
        meeting = conn.execute("SELECT id FROM meetings WHERE id = ?", (meeting_id,)).fetchone()
        if not meeting:
            raise ValueError("meeting_not_found")
        correction_count = conn.execute(
            "SELECT COUNT(*) FROM transcript_corrections WHERE meeting_id = ?",
            (meeting_id,),
        ).fetchone()[0]
        conn.execute(
            """
            INSERT INTO processing_jobs
              (meeting_id, stage, status, progress)
            VALUES (?, ?, ?, ?)
            """,
            (meeting_id, "synthesis_regeneration", "running", 0.0),
        )
        job_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]
    try:
        atoms = extract_meeting_atoms(config, meeting_id)
    except Exception as exc:
        with connect(config.paths.database_path) as conn:
            conn.execute(
                """
                UPDATE processing_jobs
                SET status = ?, progress = ?, error = ?, completed_at = CURRENT_TIMESTAMP
                WHERE id = ?
                """,
                ("failed", 1.0, str(exc), job_id),
            )
        raise
    with connect(config.paths.database_path) as conn:
        conn.execute(
            """
            UPDATE processing_jobs
            SET status = ?, progress = ?, error = ?, completed_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (
                "complete",
                1.0,
                json.dumps({"correction_count": int(correction_count)}),
                job_id,
            ),
        )
    return atoms


# Match "Speaker 2", "Speaker_002", "Speaker 12" anywhere in prose. The
# expanded patterns cover the two diarization conventions we see in the
# wild plus the model's occasional "Speaker 4" hallucination invented
# out of confirmed names. Replacement is conservative — `a team member`
# instead of guessing — because misattribution is worse than vagueness.
_SPEAKER_PLACEHOLDER_RE = re.compile(
    r"\bSpeaker[_ ]?\d{1,3}\b",
    flags=re.IGNORECASE,
)


# First-person commitment markers — used by persist_atoms when the model
# emits an action task as a direct quote ("I'll write up the scope cut")
# without filling in `owner`. "We will" / "let's" / "we should" are GROUP
# commitments and intentionally excluded — they shouldn't credit a single
# speaker. Compiled at module level so we don't pay the cost per-call.
_FIRST_PERSON_COMMIT = re.compile(
    r"^\s*(?:i (?:will|'ll|am going to|need to|plan to)|i'll|let me|"
    r"i (?:am|'m) going to|i'?d like to)\b",
    re.IGNORECASE,
)


def _scrub_speaker_placeholders(text: str) -> str:
    """Strip 'Speaker N' / 'Speaker_002' placeholders from prose fields.

    The prompt asks the model never to emit these in user-facing prose
    (it's instructed to say 'a team member' instead), but frontier and
    local models alike occasionally regress. This belt-and-braces pass
    catches leakage at persist time so the reader never sees a placeholder.
    """
    if not text:
        return text
    return _SPEAKER_PLACEHOLDER_RE.sub("a team member", text)


def _scrub_atoms_speaker_placeholders(atoms: MeetingAtoms) -> None:
    """Mutates atoms in place — runs the placeholder scrub on every
    user-facing prose field. Centralising the list here means new
    prose fields added later get covered when their authors thread
    them through here.
    """
    atoms.tldr = _scrub_speaker_placeholders(atoms.tldr)
    atoms.summary = _scrub_speaker_placeholders(atoms.summary)
    atoms.suggested_title = _scrub_speaker_placeholders(atoms.suggested_title)
    for decision in atoms.decisions:
        decision.decision = _scrub_speaker_placeholders(decision.decision)
        if decision.rationale:
            decision.rationale = _scrub_speaker_placeholders(decision.rationale)
    for oq in atoms.open_questions:
        oq.question = _scrub_speaker_placeholders(oq.question)
    for contribution in atoms.participant_contributions:
        contribution.contribution = _scrub_speaker_placeholders(contribution.contribution)
    for chapter in atoms.chapter_markers:
        chapter.summary = _scrub_speaker_placeholders(chapter.summary)
        chapter.label = _scrub_speaker_placeholders(chapter.label)
    for tension in atoms.tension_points:
        tension.title = _scrub_speaker_placeholders(tension.title)
        tension.positive_side = _scrub_speaker_placeholders(tension.positive_side)
        tension.negative_side = _scrub_speaker_placeholders(tension.negative_side)
    for stat in atoms.stat_callouts:
        stat.value = _scrub_speaker_placeholders(stat.value)
        stat.label = _scrub_speaker_placeholders(stat.label)
    for action in atoms.actions:
        action.task = _scrub_speaker_placeholders(action.task)
        if action.owner:
            scrubbed_owner = _scrub_speaker_placeholders(action.owner)
            # If the owner string was nothing BUT a placeholder, the
            # scrub yields "a team member" — drop to None so the UI
            # renders the action as unassigned rather than as a fake
            # display name.
            action.owner = (
                None
                if scrubbed_owner.strip().casefold() == "a team member"
                else scrubbed_owner
            )
    for workstream in atoms.workstreams:
        workstream.name = _scrub_speaker_placeholders(workstream.name)
        workstream.description = _scrub_speaker_placeholders(workstream.description)
    atoms.key_takeaways = [
        _scrub_speaker_placeholders(t) for t in atoms.key_takeaways
    ]


def persist_atoms(config: AppConfig, meeting_id: int, atoms: MeetingAtoms) -> None:
    # Belt-and-braces scrub of `Speaker N` placeholders that leak into
    # prose fields despite the prompt rule. Runs once on the merged
    # atoms before persistence so every downstream surface (overview,
    # exports, Reflections) sees clean prose.
    _scrub_atoms_speaker_placeholders(atoms)
    with connect(config.paths.database_path) as conn:
        conn.execute(
            "UPDATE meetings SET title = ? WHERE id = ?",
            (atoms.suggested_title, meeting_id),
        )
        conn.execute("DELETE FROM action_items WHERE meeting_id = ?", (meeting_id,))
        conn.execute(
            """
            DELETE FROM review_items
            WHERE meeting_id = ?
              AND kind IN (
                'summary', 'decision', 'workstream', 'open_question', 'uncertainty',
                'action_cluster_meta', 'executive_recap'
              )
            """,
            (meeting_id,),
        )
        conn.execute(
            """
            INSERT INTO review_items
              (meeting_id, kind, title, payload_json, confidence, source_segment_ids)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                meeting_id,
                "summary",
                atoms.suggested_title,
                json.dumps(
                    {
                        "summary": atoms.summary,
                        "tldr": atoms.tldr,
                        "participant_contributions": [
                            entry.model_dump() for entry in atoms.participant_contributions
                        ],
                        "chapter_markers": [
                            chapter.model_dump() for chapter in atoms.chapter_markers
                        ],
                        "themes": list(atoms.themes),
                        "stat_callouts": [
                            entry.model_dump() for entry in atoms.stat_callouts
                        ],
                        "tension_points": [
                            entry.model_dump() for entry in atoms.tension_points
                        ],
                        "key_takeaways": list(atoms.key_takeaways),
                        "briefing": list(atoms.briefing),
                    }
                ),
                0.8,
                "[]",
            ),
        )
        if atoms.executive_recap is not None:
            conn.execute(
                """
                INSERT INTO review_items
                  (meeting_id, kind, title, payload_json)
                VALUES (?, 'executive_recap', ?, ?)
                """,
                (
                    meeting_id,
                    atoms.suggested_title[:120],
                    atoms.executive_recap.model_dump_json(),
                ),
            )
        # Build a lookup from approved speaker labels → people.id, scoped
        # to the *confirmed speakers of this meeting* so an action whose
        # owner says "Sam" can't collide with a different "Sam" from an
        # unrelated meeting.
        owner_to_person: dict[str, int] = {}
        people_rows = conn.execute(
            """
            SELECT DISTINCT p.id, p.display_name, p.aliases
            FROM people p
            JOIN speaker_assignments sa ON sa.person_id = p.id
            WHERE sa.meeting_id = ? AND sa.confirmed_by_user = 1
            """,
            (meeting_id,),
        ).fetchall()
        for row in people_rows:
            owner_to_person[str(row["display_name"]).strip().casefold()] = int(row["id"])
            try:
                aliases = json.loads(row["aliases"] or "[]")
            except json.JSONDecodeError:
                aliases = []
            for alias in aliases:
                if isinstance(alias, str) and alias.strip():
                    owner_to_person[alias.strip().casefold()] = int(row["id"])

        # Build a (segment_id → person_id) lookup so we can infer the
        # owner of a first-person-commitment action from the speaker at
        # the segment where it was raised. Only includes segments whose
        # speakers are confirmed; unconfirmed segments don't credit
        # anyone (avoids mis-attribution).
        segment_speaker_person: dict[int, int] = {}
        for seg_row in conn.execute(
            """
            SELECT ts.id AS sid, sa.person_id
            FROM transcript_segments ts
            JOIN speaker_assignments sa
              ON sa.meeting_id = ts.meeting_id
             AND sa.diarization_speaker_id = ts.diarization_speaker_id
             AND sa.confirmed_by_user = 1
            WHERE ts.meeting_id = ?
            """,
            (meeting_id,),
        ).fetchall():
            if seg_row["person_id"] is not None:
                segment_speaker_person[int(seg_row["sid"])] = int(seg_row["person_id"])

        def _resolve_owner(action: ExtractedAction) -> int | None:
            """Walk the 3-step owner resolution (display-name → first-name
            fallback → segment speaker for first-person commitments → new
            people row when the string looks like a real name).
            """
            owner_raw = (action.owner or "").strip()
            owner_id: int | None = None
            if owner_raw:
                owner_id = owner_to_person.get(owner_raw.casefold())
                if owner_id is None:
                    token = owner_raw.split()[0].casefold().strip("@.,;:'\"")
                    candidates = {
                        person_id
                        for key, person_id in owner_to_person.items()
                        if key == token or key.split()[0] == token
                    }
                    if len(candidates) == 1:
                        owner_id = next(iter(candidates))
            if owner_id is None and _FIRST_PERSON_COMMIT.search(action.task):
                seed_seg = (
                    max(action.source_segment_ids)
                    if action.source_segment_ids
                    else None
                )
                if seed_seg is not None:
                    seg_owner = segment_speaker_person.get(int(seed_seg))
                    if seg_owner is not None:
                        owner_id = seg_owner
            if owner_id is None and owner_raw:
                looks_like_name = bool(
                    re.match(r"^[A-Z][A-Za-z'\-\.]{1,40}(\s+[A-Za-z'\-\.]{1,40}){1,3}$", owner_raw)
                )
                if looks_like_name:
                    existing = conn.execute(
                        "SELECT id FROM people WHERE lower(display_name) = ?",
                        (owner_raw.casefold(),),
                    ).fetchone()
                    if existing:
                        owner_id = int(existing["id"])
                    else:
                        cursor = conn.execute(
                            "INSERT INTO people (display_name, last_seen_at) "
                            "VALUES (?, CURRENT_TIMESTAMP)",
                            (owner_raw,),
                        )
                        owner_id = int(cursor.lastrowid)
                    owner_to_person[owner_raw.casefold()] = owner_id
            return owner_id

        owner_ids: list[int | None] = [_resolve_owner(a) for a in atoms.actions]
        clusters = _cluster_actions(atoms.actions, owner_ids)
        for cluster in clusters:
            if len(cluster) == 1:
                idx = cluster[0]
                action = atoms.actions[idx]
                conn.execute(
                    """
                    INSERT INTO action_items
                      (meeting_id, owner_person_id, text, due_date, due_date_source,
                       priority, source_segment_ids)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        meeting_id,
                        owner_ids[idx],
                        action.task,
                        action.due_date,
                        action.due_date_source,
                        action.priority,
                        json.dumps(action.source_segment_ids),
                    ),
                )
                continue
            # Cluster of 2+: write the canonical first, capture its id,
            # then write members linked to it. Canonical takes the merged
            # segment IDs (so evidence pills carry every member's
            # citations) and the resolved cluster-level due date.
            canon_idx = cluster[0]
            canonical = atoms.actions[canon_idx]
            member_actions = [atoms.actions[i] for i in cluster]
            merged_segs: list[int] = []
            for a in member_actions:
                for seg in a.source_segment_ids:
                    if seg not in merged_segs:
                        merged_segs.append(seg)
            due_date, due_date_source, due_history = _resolve_cluster_due_date(
                member_actions
            )
            cursor = conn.execute(
                """
                INSERT INTO action_items
                  (meeting_id, owner_person_id, text, due_date, due_date_source,
                   priority, source_segment_ids, cluster_role)
                VALUES (?, ?, ?, ?, ?, ?, ?, 'canonical')
                """,
                (
                    meeting_id,
                    owner_ids[canon_idx],
                    canonical.task,
                    due_date,
                    due_date_source,
                    canonical.priority,
                    json.dumps(merged_segs),
                ),
            )
            canonical_id = int(cursor.lastrowid)
            for member_idx in cluster[1:]:
                member = atoms.actions[member_idx]
                conn.execute(
                    """
                    INSERT INTO action_items
                      (meeting_id, owner_person_id, text, due_date, due_date_source,
                       priority, source_segment_ids, cluster_id, cluster_role)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'member')
                    """,
                    (
                        meeting_id,
                        owner_ids[member_idx],
                        member.task,
                        member.due_date,
                        member.due_date_source,
                        member.priority,
                        json.dumps(member.source_segment_ids),
                        canonical_id,
                    ),
                )
            if due_history:
                # Persist the supersession trail on the canonical via a
                # dedicated review_items row keyed off the action id.
                conn.execute(
                    """
                    INSERT INTO review_items
                      (meeting_id, kind, title, payload_json)
                    VALUES (?, 'action_cluster_meta', ?, ?)
                    """,
                    (
                        meeting_id,
                        f"action:{canonical_id}",
                        json.dumps({"due_date_history": due_history}),
                    ),
                )
        for decision in atoms.decisions:
            conn.execute(
                """
                INSERT INTO review_items
                  (meeting_id, kind, title, payload_json, confidence, source_segment_ids)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (
                    meeting_id,
                    "decision",
                    decision.decision[:120],
                    decision.model_dump_json(),
                    0.7,
                    json.dumps(decision.source_segment_ids),
                ),
            )
        for workstream in _top_workstreams(atoms.workstreams):
            conn.execute(
                """
                INSERT INTO review_items
                  (meeting_id, kind, title, payload_json, confidence, source_segment_ids)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (
                    meeting_id,
                    "workstream",
                    workstream.name,
                    workstream.model_dump_json(),
                    workstream.confidence,
                    json.dumps(workstream.source_segment_ids),
                ),
            )
        for question in atoms.open_questions:
            conn.execute(
                """
                INSERT INTO review_items
                  (meeting_id, kind, title, payload_json, source_segment_ids)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    meeting_id,
                    "open_question",
                    question.question[:120],
                    question.model_dump_json(),
                    json.dumps(question.source_segment_ids),
                ),
            )
        for uncertainty in atoms.uncertainties:
            conn.execute(
                """
                INSERT INTO review_items (meeting_id, kind, title, payload_json)
                VALUES (?, ?, ?, ?)
                """,
                (meeting_id, "uncertainty", uncertainty[:120], json.dumps({"text": uncertainty})),
            )


def update_meeting_summary(config: AppConfig, meeting_id: int, summary: str) -> None:
    clean_summary = summary.strip()
    if not clean_summary:
        raise ValueError("summary_required")
    with connect(config.paths.database_path) as conn:
        meeting = conn.execute("SELECT title FROM meetings WHERE id = ?", (meeting_id,)).fetchone()
        if not meeting:
            raise ValueError("meeting_not_found")
        conn.execute(
            "DELETE FROM review_items WHERE meeting_id = ? AND kind = 'summary'",
            (meeting_id,),
        )
        conn.execute(
            """
            INSERT INTO review_items
              (meeting_id, kind, title, payload_json, confidence, source_segment_ids)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                meeting_id,
                "summary",
                str(meeting["title"]),
                json.dumps({"summary": clean_summary, "edited_by_user": True}),
                1.0,
                "[]",
            ),
        )


def _format_timestamp(ms: int) -> str:
    total_seconds = int(ms / 1000)
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours:02}:{minutes:02}:{seconds:02}"
    return f"{minutes:02}:{seconds:02}"


def _top_workstreams(
    workstreams: list[ExtractedWorkstream],
    limit: int = 8,
) -> list[ExtractedWorkstream]:
    seen: set[str] = set()
    unique: list[ExtractedWorkstream] = []
    for workstream in sorted(workstreams, key=lambda item: item.confidence, reverse=True):
        key = workstream.name.strip().casefold()
        if not key or key in seen:
            continue
        seen.add(key)
        unique.append(workstream)
        if len(unique) == limit:
            break
    return unique


def _review_annotations_by_segment(conn, meeting_id: int) -> dict[int, list[str]]:
    rows = conn.execute(
        """
        SELECT kind, title, source_segment_ids
        FROM review_items
        WHERE meeting_id = ?
          AND status = 'open'
          AND kind IN ('transcript_quality', 'transcript_audit', 'speaker_confidence')
        """,
        (meeting_id,),
    ).fetchall()
    annotations: dict[int, list[str]] = {}
    for row in rows:
        try:
            segment_ids = json.loads(row["source_segment_ids"] or "[]")
        except json.JSONDecodeError:
            segment_ids = []
        for segment_id in segment_ids:
            if isinstance(segment_id, int):
                annotations.setdefault(segment_id, []).append(
                    f"{row['kind']}: {row['title']}"
                )
    return annotations


def _segment_extraction_flags(row, annotations: list[str]) -> list[str]:
    flags = list(annotations)
    text_confidence = (
        row["text_confidence"] if row["text_confidence"] is not None else row["confidence"]
    )
    speaker_confidence = (
        row["speaker_confidence"] if row["speaker_confidence"] is not None else row["confidence"]
    )
    if text_confidence is not None and float(text_confidence) < 0.55:
        flags.append(f"low content confidence {float(text_confidence):.2f}")
    if speaker_confidence is not None and float(speaker_confidence) < 0.7:
        flags.append(f"low speaker assignment confidence {float(speaker_confidence):.2f}")
    return flags
